name: Run Tests

on:
  pull_request

jobs:
  run-tests:
    runs-on: ubuntu-latest

    services:
      redis:
        image: redis:7.4
        ports:
          - 6379:6379

      mysql:
        image: mysql:8.0
        ports:
          - 3306:3306
        env:
          MYSQL_DATABASE: devops
          MYSQL_ALLOW_EMPTY_PASSWORD: yes

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4.1.7

      - name: Setup
        uses: ./.github/actions/setup
        with:
          php-version: 8.4
          coverage: xdebug

      - name: Install Dependencies
        run: composer install -q --no-interaction

      - name: Setup Application
        run: |
          cp .env.example .env
          php artisan key:generate

      - name: Run Tests
        run: php artisan test --compact --coverage --min=90